logging:
  level:
    root: info
    com.diu: debug
spring:
  datasource:
    druid:
      url: jdbc:mysql://qdm114116425.my3w.com:3306/jijiedi?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root                                      #数据库用户名
      password: 123456                                      #数据库密码
      db-type: com.alibaba.druid.pool.DruidDataSource     #数据源类型启用Druid
      driver-class-name: com.mysql.jdbc.Driver            #驱动
      filters: stat                                       #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
      max-active: 20                                      #最大连接池数量
      initial-size: 1                                     #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      max-wait: 60000                                     #获取连接时最大等待时间，单位毫秒
      min-idle: 1
      time-between-eviction-runs-millis: 60000            #1) Destroy线程会检测连接的间隔时间2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'                        #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      test-while-idle: true                               #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-on-return: false                               #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false                               #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      pool-prepared-statements: false                     #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      max-open-prepared-statements: 20                    #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
  redis:
    database: 0
    host: 182.61.20.101
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 50000
  session:
    store-type: redis
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.163.com
    username: 18761870910@163.com
    password: luo987
    default-encoding: utf-8
  mvc:
    favicon:
      enabled: false
#是否允许生成代码，生产环境设置为false
generator:
  enabled: false